# Generated by Django 5.2.14 on 2026-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='shipments_s_order_i_38988b_idx'), models.Index(fields=['user_id'], name='shipments_s_user_id_7f1b2d_idx'), models.Index(fields=['status'], name='shipments_s_status_536511_idx')],
            },
        ),
    ]
